site_name: AsyncMaxBot SDK
site_url: https://sdkinfotech.github.io/asyncmaxbot
repo_url: https://github.com/sdkinfotech/asyncmaxbot
repo_name: sdkinfotech/asyncmaxbot
edit_uri: ""

extra:
  version: "1.4.3"

theme:
  name: material
  language: ru
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: lime
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - toc:
      permalink: true

nav:
  - 'Главная': 'index.md'
  - 'Руководство API': 'api.md'
  - 'Примеры': 'examples.md' 