name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
    
    - name: Build package
      run: python -m build
    
    - name: Check package
      run: twine check dist/*
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist/

  create_release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: dist
        path: dist/
    
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          ## 🚀 Новый релиз MaxBot Python SDK
          
          ### Что нового:
          - Обновления и улучшения
          - Исправления багов
          - Новая функциональность
          
          ### Установка:
          ```bash
          pip install maxbot==${{ github.ref_name }}
          ```
          
          ### Документация:
          - [README](https://github.com/sdkinfotech/asyncmaxbot#readme)
          - [API Documentation](https://github.com/sdkinfotech/asyncmaxbot/blob/main/API_DOCUMENTATION.md)
          - [Examples](https://github.com/sdkinfotech/asyncmaxbot/tree/main/examples)
          
          ### Изменения:
          Смотрите [ROADMAP](https://github.com/sdkinfotech/asyncmaxbot/blob/main/ROADMAP.md) для подробностей.
        draft: false
        prerelease: false
    
    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/maxbot-${{ github.ref_name }}.tar.gz
        asset_name: maxbot-${{ github.ref_name }}.tar.gz
        asset_content_type: application/gzip
    
    - name: Upload Release Assets (wheel)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/maxbot-${{ github.ref_name }}-py3-none-any.whl
        asset_name: maxbot-${{ github.ref_name }}-py3-none-any.whl
        asset_content_type: application/zip 